In [35]:
import getopt
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
from func import norm_2D

- pxw: class specific probability density functions (determine by using Norm2D)
- pw: prior probabilities
- g: Determine discriminant functions

In [36]:
# Initialise values
mu = []
sgm = []
pw = np.array([0.5, 0.5]) # Prior probability
col = ['r', 'b']

mu.append(np.array([[3],[6]]))
mu.append(np.array([[3],[-2]]))
sgm.append(np.array([[0.5, 0], [0, 2]]))
sgm.append(np.array([[2, 0], [0, 2]]))

x1=np.arange(-10,10.5,0.5).reshape(-1,1)
x2=np.arange(-9,10.5,0.5).reshape(-1,1)
x_1, x_2 = np.meshgrid(x1, x2)

In [43]:
# Determine class specific probability density functions, pxw[i]
pxw = []
px = 0 # total density function
for i in range(len(mu)):
    pxw.append(norm_2D(mu[i], sgm[i], x_1, x_2))
    px += pw[i] + pxw[i]
# fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
# for i in range(len(sgm)):
#     pxw = norm_2D(mu[i], sgm[i], x_1, x_2)
#     pwpxw = pw[i]*p
#     ax.plot_surface(x_1, x_2, p, color=col[i])
# plt.show()


[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [ ]:
# Determine discriminant functions
g = []
for i in range(len(mu)):
    